INFO :: root :: 2022-01-21 00:43:26,242 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:43:26,285 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:43:26,290 :: Started server process [7660]
INFO :: uvicorn.error :: 2022-01-21 00:43:26,291 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:43:26,292 :: Application startup complete.
INFO :: root :: 2022-01-21 00:43:41,315 :: Successfully Added User Details
DEBUG :: root :: 2022-01-21 00:43:41,315 :: Added User Id is : [{'user_id': 6}]
INFO :: root :: 2022-01-21 00:44:27,978 :: Successfully Added User Details
DEBUG :: root :: 2022-01-21 00:44:27,978 :: Added User Id is : [{'user_id': 7}]
INFO :: root :: 2022-01-21 00:48:09,374 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:48:09,420 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:48:09,426 :: Started server process [7720]
INFO :: uvicorn.error :: 2022-01-21 00:48:09,426 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:48:09,427 :: Application startup complete.
INFO :: root :: 2022-01-21 00:50:28,148 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:50:28,252 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:50:28,260 :: Started server process [10116]
INFO :: uvicorn.error :: 2022-01-21 00:50:28,263 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:50:28,264 :: Application startup complete.
INFO :: root :: 2022-01-21 00:51:09,218 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:51:09,257 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:51:09,261 :: Started server process [984]
INFO :: uvicorn.error :: 2022-01-21 00:51:09,261 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:51:09,262 :: Application startup complete.
INFO :: root :: 2022-01-21 00:52:19,284 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:52:19,326 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:52:19,331 :: Started server process [7572]
INFO :: uvicorn.error :: 2022-01-21 00:52:19,332 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:52:19,332 :: Application startup complete.
INFO :: root :: 2022-01-21 00:53:57,776 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:53:57,776 :: Deleted Employee ID is : 3
ERROR :: uvicorn.error :: 2022-01-21 00:53:57,779 :: Exception in ASGI application
Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 137, in jsonable_encoder
    data = dict(obj)
TypeError: 'builtin_function_or_method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 141, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 148, in serialize_response
    return jsonable_encoder(response_content)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'builtin_function_or_method' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO :: root :: 2022-01-21 00:54:22,706 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:54:22,706 :: Deleted Employee ID is : 3
ERROR :: uvicorn.error :: 2022-01-21 00:54:22,709 :: Exception in ASGI application
Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 137, in jsonable_encoder
    data = dict(obj)
TypeError: 'builtin_function_or_method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 141, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 148, in serialize_response
    return jsonable_encoder(response_content)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'builtin_function_or_method' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO :: root :: 2022-01-21 00:55:31,987 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:55:31,987 :: Deleted Employee ID is : 3
ERROR :: uvicorn.error :: 2022-01-21 00:55:31,991 :: Exception in ASGI application
Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 137, in jsonable_encoder
    data = dict(obj)
TypeError: 'builtin_function_or_method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 141, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 148, in serialize_response
    return jsonable_encoder(response_content)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'builtin_function_or_method' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO :: root :: 2022-01-21 00:55:43,720 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:55:43,721 :: Deleted Employee ID is : 4
ERROR :: uvicorn.error :: 2022-01-21 00:55:43,723 :: Exception in ASGI application
Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 137, in jsonable_encoder
    data = dict(obj)
TypeError: 'builtin_function_or_method' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 141, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 234, in app
    response_data = await serialize_response(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 148, in serialize_response
    return jsonable_encoder(response_content)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 93, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'builtin_function_or_method' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO :: root :: 2022-01-21 00:56:36,210 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:56:36,250 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:56:36,255 :: Started server process [6500]
INFO :: uvicorn.error :: 2022-01-21 00:56:36,257 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:56:36,257 :: Application startup complete.
INFO :: root :: 2022-01-21 00:56:44,259 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:56:44,259 :: Deleted Employee ID is : 7
INFO :: root :: 2022-01-21 00:58:27,567 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:58:27,661 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:58:27,666 :: Started server process [6452]
INFO :: uvicorn.error :: 2022-01-21 00:58:27,666 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:58:27,667 :: Application startup complete.
INFO :: root :: 2022-01-21 00:58:45,939 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 00:58:45,978 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 00:58:45,982 :: Started server process [8424]
INFO :: uvicorn.error :: 2022-01-21 00:58:45,983 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 00:58:45,983 :: Application startup complete.
INFO :: root :: 2022-01-21 00:59:16,182 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:59:16,183 :: Deleted Employee ID is : 7
INFO :: root :: 2022-01-21 00:59:24,025 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:59:24,025 :: Deleted Employee ID is : 7
INFO :: root :: 2022-01-21 00:59:35,056 :: Successfully Deleted The User Details
DEBUG :: root :: 2022-01-21 00:59:35,057 :: Deleted Employee ID is : 7
INFO :: root :: 2022-01-21 01:00:41,948 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:00:42,117 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:00:42,124 :: Started server process [960]
INFO :: uvicorn.error :: 2022-01-21 01:00:42,143 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:00:42,144 :: Application startup complete.
INFO :: root :: 2022-01-21 01:05:56,581 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:05:56,627 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:05:56,634 :: Started server process [7748]
INFO :: uvicorn.error :: 2022-01-21 01:05:56,640 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:05:56,642 :: Application startup complete.
INFO :: root :: 2022-01-21 01:10:15,812 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:10:15,850 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:10:15,855 :: Started server process [5688]
INFO :: uvicorn.error :: 2022-01-21 01:10:15,856 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:10:15,857 :: Application startup complete.
INFO :: root :: 2022-01-21 01:12:07,259 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:12:09,345 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:12:09,350 :: Started server process [6428]
INFO :: uvicorn.error :: 2022-01-21 01:12:09,351 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:12:09,352 :: Application startup complete.
INFO :: root :: 2022-01-21 01:14:16,686 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:14:16,725 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:14:16,729 :: Started server process [1028]
INFO :: uvicorn.error :: 2022-01-21 01:14:16,730 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:14:16,730 :: Application startup complete.
INFO :: root :: 2022-01-21 01:18:36,628 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:18:36,667 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:18:36,674 :: Started server process [6000]
INFO :: uvicorn.error :: 2022-01-21 01:18:36,675 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:18:36,675 :: Application startup complete.
INFO :: root :: 2022-01-21 01:38:30,111 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:38:30,517 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:38:30,523 :: Started server process [9592]
INFO :: uvicorn.error :: 2022-01-21 01:38:30,524 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:38:30,524 :: Application startup complete.
INFO :: root :: 2022-01-21 01:38:49,203 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:38:49,247 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:38:49,255 :: Started server process [5560]
INFO :: uvicorn.error :: 2022-01-21 01:38:49,255 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:38:49,256 :: Application startup complete.
INFO :: root :: 2022-01-21 01:39:02,123 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:39:02,192 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:39:02,197 :: Started server process [3860]
INFO :: uvicorn.error :: 2022-01-21 01:39:02,197 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:39:02,198 :: Application startup complete.
INFO :: root :: 2022-01-21 01:39:24,741 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:39:24,777 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:39:24,783 :: Started server process [5236]
INFO :: uvicorn.error :: 2022-01-21 01:39:24,783 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:39:24,784 :: Application startup complete.
INFO :: root :: 2022-01-21 01:42:14,097 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:42:14,203 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:42:14,211 :: Started server process [7476]
INFO :: uvicorn.error :: 2022-01-21 01:42:14,211 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:42:14,212 :: Application startup complete.
ERROR :: root :: 2022-01-21 01:43:04,526 :: Error: Commands out of sync; you can't run this command now
INFO :: root :: 2022-01-21 01:44:17,052 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:44:17,086 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:44:17,093 :: Started server process [700]
INFO :: uvicorn.error :: 2022-01-21 01:44:17,094 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:44:17,094 :: Application startup complete.
INFO :: root :: 2022-01-21 01:45:56,566 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:45:56,599 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:45:56,605 :: Started server process [7040]
INFO :: uvicorn.error :: 2022-01-21 01:45:56,606 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:45:56,606 :: Application startup complete.
INFO :: root :: 2022-01-21 01:46:42,359 :: Successfully Added User Details
DEBUG :: root :: 2022-01-21 01:46:42,359 :: Verified User Id is : [{'user_id': 1}]
INFO :: root :: 2022-01-21 01:47:03,434 :: Successfully Added User Details
DEBUG :: root :: 2022-01-21 01:47:03,435 :: Verified User Id is : []
INFO :: root :: 2022-01-21 01:47:25,096 :: Successfully Added User Details
DEBUG :: root :: 2022-01-21 01:47:25,097 :: Verified User Id is : []
INFO :: root :: 2022-01-21 01:50:34,456 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:50:34,494 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:50:34,503 :: Started server process [8656]
INFO :: uvicorn.error :: 2022-01-21 01:50:34,504 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:50:34,505 :: Application startup complete.
INFO :: root :: 2022-01-21 01:52:46,178 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:52:46,211 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:52:46,218 :: Started server process [5436]
INFO :: uvicorn.error :: 2022-01-21 01:52:46,219 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:52:46,220 :: Application startup complete.
INFO :: root :: 2022-01-21 01:52:47,276 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:52:47,312 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:52:47,319 :: Started server process [272]
INFO :: uvicorn.error :: 2022-01-21 01:52:47,319 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:52:47,320 :: Application startup complete.
ERROR :: root :: 2022-01-21 01:52:57,519 :: Error: ('Incorrect User Details', 'error: id not found')
INFO :: root :: 2022-01-21 01:55:06,960 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:55:06,996 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:55:07,001 :: Started server process [6880]
INFO :: uvicorn.error :: 2022-01-21 01:55:07,001 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:55:07,002 :: Application startup complete.
ERROR :: root :: 2022-01-21 01:55:12,310 :: Error: {'error: id not found', 'Incorrect User Details'}
INFO :: root :: 2022-01-21 01:55:33,334 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:55:33,370 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:55:33,376 :: Started server process [3824]
INFO :: uvicorn.error :: 2022-01-21 01:55:33,376 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:55:33,377 :: Application startup complete.
INFO :: root :: 2022-01-21 01:56:22,271 :: Successfully Verified User Details
DEBUG :: root :: 2022-01-21 01:56:22,271 :: Verified User Id is : [{'user_id': 1}]
INFO :: root :: 2022-01-21 01:57:18,851 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 01:57:18,894 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 01:57:18,900 :: Started server process [9220]
INFO :: uvicorn.error :: 2022-01-21 01:57:18,901 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 01:57:18,902 :: Application startup complete.
INFO :: root :: 2022-01-21 01:58:20,123 :: Successfully Added User Details
DEBUG :: root :: 2022-01-21 01:58:20,124 :: Added User Id is : [{'user_id': 8}]
INFO :: root :: 2022-01-21 02:07:34,712 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 02:07:34,754 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 02:07:34,762 :: Started server process [8948]
INFO :: uvicorn.error :: 2022-01-21 02:07:34,762 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 02:07:34,763 :: Application startup complete.
ERROR :: root :: 2022-01-21 02:08:00,653 :: Error: ('Incorrect User Id', 'error: id not found')
ERROR :: root :: 2022-01-21 02:08:21,821 :: Error: ('Incorrect User Id', 'error: id not found')
INFO :: root :: 2022-01-21 02:10:28,103 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 02:10:28,725 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 02:10:28,733 :: Started server process [8484]
INFO :: uvicorn.error :: 2022-01-21 02:10:28,734 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 02:10:28,735 :: Application startup complete.
INFO :: root :: 2022-01-21 02:31:08,084 :: Trying to establish the database connection
INFO :: root :: 2022-01-21 02:31:12,166 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-21 02:31:12,172 :: Started server process [9628]
INFO :: uvicorn.error :: 2022-01-21 02:31:12,172 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-21 02:31:12,173 :: Application startup complete.
INFO :: root :: 2022-01-24 00:14:04,889 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 00:14:08,268 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 00:14:08,344 :: Started server process [7452]
INFO :: uvicorn.error :: 2022-01-24 00:14:08,345 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 00:14:08,410 :: Application startup complete.
INFO :: root :: 2022-01-24 00:16:18,476 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 00:16:18,476 :: Added User Id is : [{'user_id': 9}]
ERROR :: root :: 2022-01-24 00:16:18,476 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 00:34:00,724 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 00:34:01,294 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 00:34:01,304 :: Started server process [7016]
INFO :: uvicorn.error :: 2022-01-24 00:34:01,305 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 00:34:01,306 :: Application startup complete.
INFO :: root :: 2022-01-24 00:35:10,680 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 00:35:10,680 :: Added User Id is : [{'user_id': 10}]
ERROR :: root :: 2022-01-24 00:35:10,680 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 00:36:03,873 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 00:36:03,912 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 00:36:03,918 :: Started server process [6340]
INFO :: uvicorn.error :: 2022-01-24 00:36:03,919 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 00:36:03,919 :: Application startup complete.
INFO :: root :: 2022-01-24 00:41:08,708 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 00:41:09,071 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 00:41:09,077 :: Started server process [8176]
INFO :: uvicorn.error :: 2022-01-24 00:41:09,078 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 00:41:09,078 :: Application startup complete.
INFO :: root :: 2022-01-24 00:41:48,410 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 00:41:48,410 :: Added User Id is : [{'user_id': 10}, {'user_id': 11}]
ERROR :: root :: 2022-01-24 00:41:48,411 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 00:47:36,960 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 00:47:37,816 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 00:47:37,826 :: Started server process [4864]
INFO :: uvicorn.error :: 2022-01-24 00:47:37,827 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 00:47:37,828 :: Application startup complete.
INFO :: root :: 2022-01-24 00:47:58,073 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 00:47:58,087 :: Added User Id is : [{'user_id': 10}, {'user_id': 11}, {'user_id': 12}]
ERROR :: root :: 2022-01-24 00:47:58,088 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 00:48:17,452 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 00:48:17,452 :: Added User Id is : [{'user_id': 13}]
ERROR :: root :: 2022-01-24 00:48:17,453 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 01:07:55,944 :: Trying to establish the database connection
ERROR :: root :: 2022-01-24 01:08:27,889 :: Connection not Established
INFO :: root :: 2022-01-24 01:10:26,318 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:10:30,529 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:10:30,589 :: Started server process [2296]
INFO :: uvicorn.error :: 2022-01-24 01:10:30,590 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:10:30,666 :: Application startup complete.
ERROR :: root :: 2022-01-24 01:12:25,886 :: Error: 1146 (42S02): Table 'book_store.user_details' doesn't exist
INFO :: root :: 2022-01-24 01:13:17,054 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 01:13:17,055 :: Added User Id is : [{'user_id': 1}]
ERROR :: root :: 2022-01-24 01:13:17,055 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 01:16:21,257 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:16:23,318 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:16:23,356 :: Started server process [5516]
INFO :: uvicorn.error :: 2022-01-24 01:16:23,357 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:16:23,367 :: Application startup complete.
INFO :: root :: 2022-01-24 01:23:28,294 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:23:29,169 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:23:29,175 :: Started server process [5196]
INFO :: uvicorn.error :: 2022-01-24 01:23:29,176 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:23:29,176 :: Application startup complete.
INFO :: root :: 2022-01-24 01:25:30,935 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:25:30,977 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:25:30,983 :: Started server process [3836]
INFO :: uvicorn.error :: 2022-01-24 01:25:30,984 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:25:30,985 :: Application startup complete.
INFO :: root :: 2022-01-24 01:28:55,871 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:28:55,911 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:28:55,918 :: Started server process [1844]
INFO :: uvicorn.error :: 2022-01-24 01:28:55,918 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:28:55,919 :: Application startup complete.
INFO :: root :: 2022-01-24 01:32:42,249 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:32:42,293 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:32:42,302 :: Started server process [7808]
INFO :: uvicorn.error :: 2022-01-24 01:32:42,303 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:32:42,306 :: Application startup complete.
INFO :: root :: 2022-01-24 01:36:58,282 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:36:58,318 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:36:58,324 :: Started server process [4948]
INFO :: uvicorn.error :: 2022-01-24 01:36:58,324 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:36:58,325 :: Application startup complete.
INFO :: root :: 2022-01-24 01:38:12,058 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:38:12,096 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:38:12,102 :: Started server process [6432]
INFO :: uvicorn.error :: 2022-01-24 01:38:12,103 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:38:12,104 :: Application startup complete.
INFO :: root :: 2022-01-24 01:38:20,744 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:38:20,782 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:38:20,790 :: Started server process [6428]
INFO :: uvicorn.error :: 2022-01-24 01:38:20,791 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:38:20,791 :: Application startup complete.
INFO :: root :: 2022-01-24 01:38:33,713 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:38:33,760 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:38:33,769 :: Started server process [4920]
INFO :: uvicorn.error :: 2022-01-24 01:38:33,770 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:38:33,771 :: Application startup complete.
INFO :: root :: 2022-01-24 01:40:49,997 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:40:50,035 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:40:50,043 :: Started server process [196]
INFO :: uvicorn.error :: 2022-01-24 01:40:50,043 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:40:50,044 :: Application startup complete.
INFO :: root :: 2022-01-24 01:44:08,018 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:44:08,059 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:44:08,068 :: Started server process [3340]
INFO :: uvicorn.error :: 2022-01-24 01:44:08,069 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:44:08,069 :: Application startup complete.
INFO :: root :: 2022-01-24 01:44:58,885 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 01:44:58,927 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 01:44:58,934 :: Started server process [7736]
INFO :: uvicorn.error :: 2022-01-24 01:44:58,935 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 01:44:58,935 :: Application startup complete.
INFO :: uvicorn.error :: 2022-01-24 01:51:17,970 :: Shutting down
INFO :: root :: 2022-01-24 02:02:03,351 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 02:02:03,872 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 02:02:03,883 :: Started server process [7952]
INFO :: uvicorn.error :: 2022-01-24 02:02:03,884 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 02:02:03,884 :: Application startup complete.
INFO :: root :: 2022-01-24 02:03:53,860 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 02:03:53,895 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 02:03:53,905 :: Started server process [7148]
INFO :: uvicorn.error :: 2022-01-24 02:03:53,906 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 02:03:53,907 :: Application startup complete.
INFO :: root :: 2022-01-24 02:04:08,762 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 02:04:08,804 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 02:04:08,822 :: Started server process [4720]
INFO :: uvicorn.error :: 2022-01-24 02:04:08,927 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 02:04:08,930 :: Application startup complete.
ERROR :: root :: 2022-01-24 02:06:51,315 :: error caught :'UserOperation' object has no attribute 'add_book_to_db'
INFO :: root :: 2022-01-24 02:09:19,937 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 02:09:19,988 :: Database Connection is Established
INFO :: root :: 2022-01-24 02:09:19,989 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 02:09:20,009 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 02:09:20,018 :: Started server process [4960]
INFO :: uvicorn.error :: 2022-01-24 02:09:20,018 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 02:09:20,019 :: Application startup complete.
INFO :: root :: 2022-01-24 02:09:33,075 :: Successfully added one book Details
INFO :: uvicorn.error :: 2022-01-24 07:53:53,913 :: Shutting down
INFO :: uvicorn.error :: 2022-01-24 07:53:54,015 :: Waiting for application shutdown.
INFO :: uvicorn.error :: 2022-01-24 07:53:54,016 :: Application shutdown complete.
INFO :: uvicorn.error :: 2022-01-24 07:53:54,017 :: Finished server process [4960]
INFO :: root :: 2022-01-24 08:04:20,687 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:04:21,767 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:04:21,790 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:04:21,813 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:04:21,839 :: Started server process [7444]
INFO :: uvicorn.error :: 2022-01-24 08:04:21,840 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:04:21,850 :: Application startup complete.
ERROR :: root :: 2022-01-24 08:11:23,654 :: Error: 'BooksOperation' object has no attribute 'add_user'
INFO :: root :: 2022-01-24 08:14:56,006 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:14:56,569 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:14:56,877 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:14:56,904 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:14:56,918 :: Started server process [4808]
INFO :: uvicorn.error :: 2022-01-24 08:14:56,918 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:14:56,920 :: Application startup complete.
INFO :: root :: 2022-01-24 08:15:47,335 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:15:47,374 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:15:47,376 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:15:47,403 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:15:47,415 :: Started server process [8296]
INFO :: uvicorn.error :: 2022-01-24 08:15:47,416 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:15:47,417 :: Application startup complete.
INFO :: root :: 2022-01-24 08:16:55,771 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:16:55,806 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:16:55,808 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:16:55,827 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:16:55,840 :: Started server process [9144]
INFO :: uvicorn.error :: 2022-01-24 08:16:55,841 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:16:55,841 :: Application startup complete.
INFO :: root :: 2022-01-24 08:17:50,504 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:17:51,547 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:17:51,660 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:17:51,694 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:17:51,707 :: Started server process [6892]
INFO :: uvicorn.error :: 2022-01-24 08:17:51,712 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:17:51,713 :: Application startup complete.
INFO :: root :: 2022-01-24 08:18:51,694 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:18:51,694 :: Added User Id is : [{'user_id': 1}]
ERROR :: root :: 2022-01-24 08:18:51,694 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 08:48:09,920 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:48:20,435 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:48:20,476 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:48:20,518 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:48:20,672 :: Started server process [3644]
INFO :: uvicorn.error :: 2022-01-24 08:48:20,687 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:48:20,713 :: Application startup complete.
INFO :: root :: 2022-01-24 08:48:24,013 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:48:24,014 :: Added User Id is : [{'user_id': 2}]
ERROR :: root :: 2022-01-24 08:48:24,014 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 08:48:24,946 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:48:24,946 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}]
ERROR :: root :: 2022-01-24 08:48:24,946 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 08:49:05,865 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:49:05,865 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}]
ERROR :: root :: 2022-01-24 08:49:05,865 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 08:49:52,377 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:49:52,377 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}]
ERROR :: root :: 2022-01-24 08:49:52,378 :: Error: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 08:53:52,373 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:54:08,644 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:54:08,755 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:54:08,789 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:54:09,048 :: Started server process [7880]
INFO :: uvicorn.error :: 2022-01-24 08:54:09,050 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:54:09,081 :: Application startup complete.
INFO :: root :: 2022-01-24 08:54:40,901 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:54:41,037 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:54:41,040 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:54:41,066 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:54:41,076 :: Started server process [6020]
INFO :: uvicorn.error :: 2022-01-24 08:54:41,076 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:54:41,077 :: Application startup complete.
INFO :: root :: 2022-01-24 08:55:00,810 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:55:00,811 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}]
INFO :: root :: 2022-01-24 08:56:27,313 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:56:27,482 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:56:27,484 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:56:27,505 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:56:27,514 :: Started server process [4816]
INFO :: uvicorn.error :: 2022-01-24 08:56:27,515 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:56:27,515 :: Application startup complete.
INFO :: root :: 2022-01-24 08:56:43,167 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:56:43,204 :: Database Connection is Established
INFO :: root :: 2022-01-24 08:56:43,205 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 08:56:43,232 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 08:56:43,244 :: Started server process [8852]
INFO :: uvicorn.error :: 2022-01-24 08:56:43,244 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 08:56:43,245 :: Application startup complete.
INFO :: root :: 2022-01-24 08:57:06,121 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 08:57:06,122 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}]
ERROR :: uvicorn.error :: 2022-01-24 08:57:06,124 :: Exception in ASGI application
Traceback (most recent call last):
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "e:\database\book_store_app\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\applications.py", line 211, in __call__
    await super().__call__(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "e:\database\book_store_app\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "e:\database\book_store_app\venv\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File ".\main.py", line 68, in register_user
    token_id = JwtHandler.encode_token(user_id)
  File ".\jwt_handler\jwt_handler.py", line 20, in encode_token
    token_id = jwt.encode(payload, "users@678$registered9090")
  File "e:\database\book_store_app\venv\lib\site-packages\jwt\api_jwt.py", line 59, in encode
    json_payload = json.dumps(
  File "E:\Python3Install\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "E:\Python3Install\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "E:\Python3Install\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Python3Install\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type timedelta is not JSON serializable
INFO :: root :: 2022-01-24 09:05:23,162 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 09:05:25,305 :: Database Connection is Established
INFO :: root :: 2022-01-24 09:05:25,399 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 09:05:25,419 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 09:05:25,436 :: Started server process [7244]
INFO :: uvicorn.error :: 2022-01-24 09:05:25,437 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 09:05:25,440 :: Application startup complete.
INFO :: root :: 2022-01-24 09:08:20,654 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 09:08:20,706 :: Database Connection is Established
INFO :: root :: 2022-01-24 09:08:20,726 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 09:08:20,755 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 09:08:20,767 :: Started server process [8760]
INFO :: uvicorn.error :: 2022-01-24 09:08:20,767 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 09:08:20,768 :: Application startup complete.
INFO :: root :: 2022-01-24 09:12:13,057 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 09:12:13,674 :: Database Connection is Established
INFO :: root :: 2022-01-24 09:12:13,701 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 09:12:13,729 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 09:12:13,742 :: Started server process [8944]
INFO :: uvicorn.error :: 2022-01-24 09:12:13,743 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 09:12:13,744 :: Application startup complete.
INFO :: root :: 2022-01-24 11:10:08,959 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:10:09,885 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:10:09,938 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:10:09,962 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:10:09,971 :: Started server process [2484]
INFO :: uvicorn.error :: 2022-01-24 11:10:09,972 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:10:09,973 :: Application startup complete.
INFO :: root :: 2022-01-24 11:12:18,451 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 11:12:18,452 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}, {'user_id': 8}]
ERROR :: root :: 2022-01-24 11:12:18,453 :: Error: module 'datetime' has no attribute 'now'
INFO :: root :: 2022-01-24 11:14:25,596 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:14:25,993 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:14:26,041 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:14:26,069 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:14:26,090 :: Started server process [2424]
INFO :: uvicorn.error :: 2022-01-24 11:14:26,096 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:14:26,098 :: Application startup complete.
INFO :: root :: 2022-01-24 11:14:48,478 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 11:14:48,478 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}, {'user_id': 8}, {'user_id': 9}]
ERROR :: root :: 2022-01-24 11:14:48,478 :: Error: module 'datetime' has no attribute 'now'
INFO :: root :: 2022-01-24 11:16:05,634 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:16:05,678 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:16:05,680 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:16:05,702 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:16:05,712 :: Started server process [7728]
INFO :: uvicorn.error :: 2022-01-24 11:16:05,713 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:16:05,714 :: Application startup complete.
INFO :: root :: 2022-01-24 11:16:05,925 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 11:16:05,926 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}, {'user_id': 8}, {'user_id': 9}, {'user_id': 10}]
ERROR :: root :: 2022-01-24 11:16:05,926 :: Error: unsupported operand type(s) for +: 'type' and 'datetime.timedelta'
INFO :: root :: 2022-01-24 11:17:54,028 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:17:54,074 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:17:54,076 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:17:54,101 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:17:54,109 :: Started server process [6612]
INFO :: uvicorn.error :: 2022-01-24 11:17:54,110 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:17:54,110 :: Application startup complete.
INFO :: root :: 2022-01-24 11:18:04,182 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 11:18:04,182 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}, {'user_id': 8}, {'user_id': 9}, {'user_id': 10}, {'user_id': 11}]
ERROR :: root :: 2022-01-24 11:18:05,190 :: Error: 2 validation errors for MessageSchema
body
  str type expected (type=type_error.str)
body
  value is not a valid list (type=type_error.list)
INFO :: root :: 2022-01-24 11:19:55,575 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:19:55,615 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:19:55,617 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:19:55,642 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:19:55,654 :: Started server process [5924]
INFO :: uvicorn.error :: 2022-01-24 11:19:55,655 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:19:55,655 :: Application startup complete.
INFO :: root :: 2022-01-24 11:20:05,322 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 11:20:05,323 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}, {'user_id': 8}, {'user_id': 9}, {'user_id': 10}, {'user_id': 11}, {'user_id': 12}]
ERROR :: root :: 2022-01-24 11:20:05,324 :: Error: 2 validation errors for MessageSchema
body
  str type expected (type=type_error.str)
body
  value is not a valid list (type=type_error.list)
INFO :: root :: 2022-01-24 11:24:10,653 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:24:11,815 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:24:11,931 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:24:11,979 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:24:11,999 :: Started server process [6588]
INFO :: uvicorn.error :: 2022-01-24 11:24:12,000 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:24:12,001 :: Application startup complete.
INFO :: root :: 2022-01-24 11:24:12,263 :: Successfully Added User Details
DEBUG :: root :: 2022-01-24 11:24:12,263 :: Added User Id is : [{'user_id': 2}, {'user_id': 3}, {'user_id': 4}, {'user_id': 5}, {'user_id': 6}, {'user_id': 7}, {'user_id': 8}, {'user_id': 9}, {'user_id': 10}, {'user_id': 11}, {'user_id': 12}, {'user_id': 13}]
INFO :: root :: 2022-01-24 11:42:11,643 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:42:13,134 :: Database Connection is Established
INFO :: root :: 2022-01-24 11:42:13,569 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 11:42:13,606 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 11:42:13,649 :: Started server process [7064]
INFO :: uvicorn.error :: 2022-01-24 11:42:13,650 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 11:42:13,651 :: Application startup complete.
INFO :: root :: 2022-01-24 12:12:37,828 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:12:37,871 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:12:37,881 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:12:37,905 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:12:37,910 :: Started server process [3652]
INFO :: uvicorn.error :: 2022-01-24 12:12:37,911 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:12:37,911 :: Application startup complete.
INFO :: root :: 2022-01-24 12:14:15,370 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:14:15,403 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:14:15,412 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:14:15,431 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:14:15,434 :: Started server process [2500]
INFO :: uvicorn.error :: 2022-01-24 12:14:15,435 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:14:15,435 :: Application startup complete.
INFO :: root :: 2022-01-24 12:16:47,768 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:16:47,811 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:16:48,048 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:16:48,076 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:16:48,082 :: Started server process [2668]
INFO :: uvicorn.error :: 2022-01-24 12:16:48,082 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:16:48,084 :: Application startup complete.
INFO :: root :: 2022-01-24 12:17:13,197 :: Successfully retrieved all books Details 
INFO :: root :: 2022-01-24 12:19:24,508 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:19:24,542 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:19:24,555 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:19:24,574 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:20:59,290 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:20:59,328 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:20:59,346 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:20:59,376 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:22:01,576 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:22:01,617 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:22:01,629 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:22:01,648 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:22:01,657 :: Started server process [8664]
INFO :: uvicorn.error :: 2022-01-24 12:22:01,658 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:22:01,658 :: Application startup complete.
INFO :: root :: 2022-01-24 12:23:05,443 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:23:05,486 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:23:05,496 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:23:05,518 :: Database Connection is Established
ERROR :: uvicorn.error :: 2022-01-24 12:23:05,527 :: Error loading ASGI app. Attribute "app" not found in module "main".
INFO :: root :: 2022-01-24 12:32:21,535 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:32:23,693 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:32:23,762 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:32:23,789 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:32:23,909 :: Started server process [2972]
INFO :: uvicorn.error :: 2022-01-24 12:32:23,910 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:32:23,919 :: Application startup complete.
INFO :: root :: 2022-01-24 12:39:05,438 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:39:05,472 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:39:05,483 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:39:05,503 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:39:05,513 :: Started server process [5332]
INFO :: uvicorn.error :: 2022-01-24 12:39:05,514 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:39:05,515 :: Application startup complete.
INFO :: root :: 2022-01-24 12:41:20,663 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:41:20,702 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:41:20,715 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:41:20,732 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:41:20,740 :: Started server process [7504]
INFO :: uvicorn.error :: 2022-01-24 12:41:20,741 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:41:20,742 :: Application startup complete.
INFO :: root :: 2022-01-24 12:48:59,332 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:49:00,697 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:49:00,865 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:49:00,888 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:49:00,899 :: Started server process [9136]
INFO :: uvicorn.error :: 2022-01-24 12:49:00,900 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:49:00,900 :: Application startup complete.
INFO :: root :: 2022-01-24 12:49:56,501 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:49:56,543 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:49:56,653 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:49:56,676 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:49:56,687 :: Started server process [2420]
INFO :: uvicorn.error :: 2022-01-24 12:49:56,687 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:49:56,688 :: Application startup complete.
INFO :: root :: 2022-01-24 12:50:49,109 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:50:49,150 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:50:49,166 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:50:49,190 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:50:49,201 :: Started server process [8736]
INFO :: uvicorn.error :: 2022-01-24 12:50:49,202 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:50:49,203 :: Application startup complete.
INFO :: root :: 2022-01-24 12:51:21,144 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:51:21,177 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:51:21,191 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:51:21,215 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:51:21,226 :: Started server process [204]
INFO :: uvicorn.error :: 2022-01-24 12:51:21,227 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:51:21,228 :: Application startup complete.
INFO :: root :: 2022-01-24 12:51:34,619 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:51:34,665 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:51:34,681 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:51:34,706 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:51:34,716 :: Started server process [8092]
INFO :: uvicorn.error :: 2022-01-24 12:51:34,716 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:51:34,717 :: Application startup complete.
INFO :: root :: 2022-01-24 12:52:07,414 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:52:07,458 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:52:24,324 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:52:24,354 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:52:24,370 :: Started server process [7432]
INFO :: uvicorn.error :: 2022-01-24 12:52:24,371 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:52:24,372 :: Application startup complete.
INFO :: root :: 2022-01-24 12:53:13,296 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:53:13,335 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:53:13,348 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:53:13,369 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:53:13,384 :: Started server process [4108]
INFO :: uvicorn.error :: 2022-01-24 12:53:13,385 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:53:13,385 :: Application startup complete.
INFO :: root :: 2022-01-24 12:57:30,239 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:57:31,506 :: Database Connection is Established
INFO :: root :: 2022-01-24 12:57:31,567 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 12:57:31,589 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 12:57:31,598 :: Started server process [5196]
INFO :: uvicorn.error :: 2022-01-24 12:57:31,599 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 12:57:31,599 :: Application startup complete.
INFO :: root :: 2022-01-24 13:36:45,388 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:36:45,595 :: Database Connection is Established
INFO :: root :: 2022-01-24 13:36:45,641 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:36:45,672 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 13:36:45,684 :: Started server process [2412]
INFO :: uvicorn.error :: 2022-01-24 13:36:45,685 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 13:36:45,686 :: Application startup complete.
INFO :: root :: 2022-01-24 13:39:29,424 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:39:29,460 :: Database Connection is Established
INFO :: root :: 2022-01-24 13:39:29,491 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:39:29,513 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 13:39:29,524 :: Started server process [8312]
INFO :: uvicorn.error :: 2022-01-24 13:39:29,525 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 13:39:29,525 :: Application startup complete.
INFO :: root :: 2022-01-24 13:40:28,221 :: Successfully retrieved  book Details
INFO :: root :: 2022-01-24 13:40:57,445 :: updated the details with book id 112 
ERROR :: root :: 2022-01-24 13:42:39,329 :: error caught :'BooksOperation' object has no attribute 'show_user_data'
INFO :: root :: 2022-01-24 13:43:52,735 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:43:52,868 :: Database Connection is Established
INFO :: root :: 2022-01-24 13:43:52,883 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:43:52,909 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 13:43:52,917 :: Started server process [452]
INFO :: uvicorn.error :: 2022-01-24 13:43:52,918 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 13:43:52,919 :: Application startup complete.
INFO :: root :: 2022-01-24 13:43:58,905 :: deleted book by using book_id 0
INFO :: root :: 2022-01-24 13:59:56,244 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 13:59:56,283 :: Database Connection is Established
INFO :: root :: 2022-01-24 14:03:52,027 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 14:03:52,067 :: Database Connection is Established
INFO :: root :: 2022-01-24 14:03:52,086 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 14:03:52,113 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 14:03:52,127 :: Started server process [7828]
INFO :: uvicorn.error :: 2022-01-24 14:03:52,128 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 14:03:52,129 :: Application startup complete.
INFO :: root :: 2022-01-24 14:06:18,359 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 14:06:18,394 :: Database Connection is Established
INFO :: root :: 2022-01-24 14:06:18,408 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 14:06:18,433 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 14:06:18,442 :: Started server process [7068]
INFO :: uvicorn.error :: 2022-01-24 14:06:18,443 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 14:06:18,443 :: Application startup complete.
INFO :: root :: 2022-01-24 14:09:14,559 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 14:09:14,603 :: Database Connection is Established
INFO :: root :: 2022-01-24 14:09:14,619 :: Trying to establish the database connection
INFO :: root :: 2022-01-24 14:09:14,645 :: Database Connection is Established
INFO :: uvicorn.error :: 2022-01-24 14:09:14,653 :: Started server process [9000]
INFO :: uvicorn.error :: 2022-01-24 14:09:14,654 :: Waiting for application startup.
INFO :: uvicorn.error :: 2022-01-24 14:09:14,655 :: Application startup complete.
INFO :: root :: 2022-01-24 14:10:49,307 :: Successfully added one book Details
INFO :: root :: 2022-01-24 14:11:07,632 :: Successfully retrieved all books Details 
INFO :: root :: 2022-01-24 14:11:36,099 :: Successfully retrieved  book Details
